FROM node:14 As build

WORKDIR /opt/app-root

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

FROM node:14-alpine3.12 as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/app-root

COPY package.json .
COPY package-lock.json .

RUN npm install --only=production

COPY . .

COPY --from=build /opt/app-root/dist ./dist

EXPOSE 3333

CMD ["node", "dist/main"]